[${project.name}][${env:SERVER_PORT}] 2025-05-05 10:00:41,220 INFO [lettuce-nioEventLoop-4-2][AbstractInternalLogger.java:219] - [null, java.io.IOException: 远程主机强迫关闭了一个现有的连接。, java.io.IOException: 远程主机强迫关闭了一个现有的连接。] Unexpected exception during request: [null, java.io.IOException: 远程主机强迫关闭了一个现有的连接。, java.io.IOException: 远程主机强迫关闭了一个现有的连接。]
[${project.name}][${env:SERVER_PORT}] 2025-05-05 10:00:41,220 INFO [lettuce-nioEventLoop-4-1][AbstractInternalLogger.java:219] - [null, java.io.IOException: 远程主机强迫关闭了一个现有的连接。, java.io.IOException: 远程主机强迫关闭了一个现有的连接。] Unexpected exception during request: [null, java.io.IOException: 远程主机强迫关闭了一个现有的连接。, java.io.IOException: 远程主机强迫关闭了一个现有的连接。]
[${project.name}][${env:SERVER_PORT}] 2025-05-05 10:00:41,256 INFO [lettuce-eventExecutorLoop-1-5][AbstractInternalLogger.java:173] - Reconnecting, last destination was localhost/127.0.0.1:6379
[${project.name}][${env:SERVER_PORT}] 2025-05-05 10:00:41,256 INFO [lettuce-eventExecutorLoop-1-6][AbstractInternalLogger.java:173] - Reconnecting, last destination was localhost/127.0.0.1:6379
[${project.name}][${env:SERVER_PORT}] 2025-05-05 10:00:43,300 WARN [lettuce-nioEventLoop-4-3][AbstractInternalLogger.java:176] - Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
[${project.name}][${env:SERVER_PORT}] 2025-05-05 10:00:43,300 WARN [lettuce-nioEventLoop-4-4][AbstractInternalLogger.java:176] - Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
[${project.name}][${env:SERVER_PORT}] 2025-05-05 10:00:47,554 INFO [lettuce-eventExecutorLoop-1-4][AbstractInternalLogger.java:173] - Reconnecting, last destination was localhost:6379
[${project.name}][${env:SERVER_PORT}] 2025-05-05 10:00:47,554 INFO [lettuce-eventExecutorLoop-1-3][AbstractInternalLogger.java:173] - Reconnecting, last destination was localhost:6379
[${project.name}][${env:SERVER_PORT}] 2025-05-05 10:00:49,585 WARN [lettuce-nioEventLoop-4-2][AbstractInternalLogger.java:176] - Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
[${project.name}][${env:SERVER_PORT}] 2025-05-05 10:00:49,585 WARN [lettuce-nioEventLoop-4-1][AbstractInternalLogger.java:176] - Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
[${project.name}][${env:SERVER_PORT}] 2025-05-05 10:00:53,864 INFO [lettuce-eventExecutorLoop-1-2][AbstractInternalLogger.java:173] - Reconnecting, last destination was localhost:6379
[${project.name}][${env:SERVER_PORT}] 2025-05-05 10:00:53,864 INFO [lettuce-eventExecutorLoop-1-8][AbstractInternalLogger.java:173] - Reconnecting, last destination was localhost:6379
[${project.name}][${env:SERVER_PORT}] 2025-05-05 10:00:55,896 WARN [lettuce-nioEventLoop-4-8][AbstractInternalLogger.java:176] - Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
[${project.name}][${env:SERVER_PORT}] 2025-05-05 10:00:55,896 WARN [lettuce-nioEventLoop-4-7][AbstractInternalLogger.java:176] - Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
[${project.name}][${env:SERVER_PORT}] 2025-05-05 10:01:00,956 INFO [lettuce-eventExecutorLoop-1-1][AbstractInternalLogger.java:173] - Reconnecting, last destination was localhost:6379
[${project.name}][${env:SERVER_PORT}] 2025-05-05 10:01:00,956 INFO [lettuce-eventExecutorLoop-1-7][AbstractInternalLogger.java:173] - Reconnecting, last destination was localhost:6379
[${project.name}][${env:SERVER_PORT}] 2025-05-05 10:01:02,976 WARN [lettuce-nioEventLoop-4-5][AbstractInternalLogger.java:176] - Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
[${project.name}][${env:SERVER_PORT}] 2025-05-05 10:01:02,991 WARN [lettuce-nioEventLoop-4-6][AbstractInternalLogger.java:176] - Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
[${project.name}][${env:SERVER_PORT}] 2025-05-05 10:01:08,161 INFO [lettuce-eventExecutorLoop-1-4][AbstractInternalLogger.java:173] - Reconnecting, last destination was localhost:6379
[${project.name}][${env:SERVER_PORT}] 2025-05-05 10:01:08,161 INFO [lettuce-eventExecutorLoop-1-3][AbstractInternalLogger.java:173] - Reconnecting, last destination was localhost:6379
[${project.name}][${env:SERVER_PORT}] 2025-05-05 10:01:10,191 WARN [lettuce-nioEventLoop-4-2][AbstractInternalLogger.java:176] - Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
[${project.name}][${env:SERVER_PORT}] 2025-05-05 10:01:10,205 WARN [lettuce-nioEventLoop-4-1][AbstractInternalLogger.java:176] - Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
[${project.name}][${env:SERVER_PORT}] 2025-05-05 10:01:14,357 INFO [lettuce-eventExecutorLoop-1-6][AbstractInternalLogger.java:173] - Reconnecting, last destination was localhost:6379
[${project.name}][${env:SERVER_PORT}] 2025-05-05 10:01:14,357 INFO [lettuce-eventExecutorLoop-1-5][AbstractInternalLogger.java:173] - Reconnecting, last destination was localhost:6379
[${project.name}][${env:SERVER_PORT}] 2025-05-05 10:01:16,383 WARN [lettuce-nioEventLoop-4-4][AbstractInternalLogger.java:176] - Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
[${project.name}][${env:SERVER_PORT}] 2025-05-05 10:01:16,383 WARN [lettuce-nioEventLoop-4-3][AbstractInternalLogger.java:176] - Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
[${project.name}][${env:SERVER_PORT}] 2025-05-05 10:01:24,656 INFO [lettuce-eventExecutorLoop-1-7][AbstractInternalLogger.java:173] - Reconnecting, last destination was localhost:6379
[${project.name}][${env:SERVER_PORT}] 2025-05-05 10:01:24,656 INFO [lettuce-eventExecutorLoop-1-1][AbstractInternalLogger.java:173] - Reconnecting, last destination was localhost:6379
[${project.name}][${env:SERVER_PORT}] 2025-05-05 10:01:24,659 INFO [lettuce-nioEventLoop-4-6][ReconnectionHandler.java:177] - Reconnected to localhost:6379
[${project.name}][${env:SERVER_PORT}] 2025-05-05 10:01:24,660 INFO [lettuce-nioEventLoop-4-5][ReconnectionHandler.java:177] - Reconnected to localhost:6379
[${project.name}][${env:SERVER_PORT}] 2025-05-05 10:06:28,910 INFO [http-nio-56085-exec-5][QCloudSmsService.java:55] - 给手机号：18866668 发送验证码：826451
[${project.name}][${env:SERVER_PORT}] 2025-05-05 10:18:54,556 INFO [http-nio-56085-exec-1][QCloudSmsService.java:55] - 给手机号：188666688 发送验证码：347045
